const keyArr = [
  "KNOWING/birthday",
  "KNOWING/isMarriedValue",
  "KNOWING/isNewCouple",
  "KNOWING/isFirstTime",
  "KNOWING/yearIncome",
  "KNOWING/supportAmount",
  "KNOWING/depositAmount",
  "KNOWING/isSingleParent",
  "KNOWING/isHavingKids",
  "KNOWING/isDisabled",
  "KNOWING/isMultiCultural",
  "KNOWING/havingNoHouse",
  "KNOWING/kidsCount",
  "KNOWING/isAbleDidimdol",
  "KNOWING/monthlySpending",
  "KNOWING/residualLoan",
  "KNOWING/borrowingYear",
  "KNOWING/confirmingLoanBank",
  "KNOWING/getDidimdolInterest",
  "KNOWING/getDidimdolLimit",
  "KNOWING/internationalAge",
  "KNOWING/isMarried",
  "KNOWING/getDidimdolPrimeRate",
  "KNOWING/isAbleConfirmingLoan",
  "KNOWING/getConfirmingLoanInterest",
  "KNOWING/getConfirmingLoanLimit",
  "KNOWING/getDsr",
  "KNOWING/getSoulGatheringAmount",
] as const;

export default keyArr;
