name: Our CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node modules # node modules 캐싱
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Deploy
        artifacts:
          paths:
            - build/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://soul-gathering-calculator
